volumes:

  minio-data:
    driver: local

services:
  ## Minio config
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio

  postgres-app:
    container_name: postgres-app
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data/postgres
    volumes:
      - ./postgres-app:/data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: -p 5432
    restart: unless-stopped
